apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: kwok-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.kwok.aiinfra.dev
          allocationMode: ExactCount
          count: 1
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: empty-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: empty-gpu.kwok.aiinfra.dev
          allocationMode: ExactCount
          count: 1
